/**
 * pdfGenerator.js — Professional PDF generation engine for CS Simulator.
 * Generates three types of PDFs: Full Notes, Interview Prep, and Cheat Sheet.
 * Uses jsPDF for client-side PDF generation with branded styling.
 */
import { jsPDF } from 'jspdf';
import { NOTES_DATA } from '../data/notesData';

/* ═══════════════════════════════════════
   DESIGN TOKENS
   ═══════════════════════════════════════ */
const COLORS = {
  black: [0, 0, 0],
  white: [255, 255, 255],
  yellow: [255, 217, 61],       // --yellow
  cyan: [102, 217, 239],        // --cyan
  pink: [255, 107, 157],        // --pink
  green: [168, 230, 207],       // --green
  orange: [255, 179, 71],       // --orange
  purple: [179, 157, 219],      // --purple
  gray: [120, 120, 120],
  lightGray: [245, 245, 247],
  darkGray: [50, 50, 50],       // Soft black for body text
};

const MARGIN = { top: 32, bottom: 30, left: 25, right: 25 };
const PAGE_WIDTH = 210; // A4
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN.left - MARGIN.right;

/* ═══════════════════════════════════════
   HELPER UTILITIES
   ═══════════════════════════════════════ */

/**
 * cleanTextForPdf: Strips emojis and translates extended Unicode chars
 * (Greek, math symbols, etc.) into clean, printable WinAnsi ASCII equivalents.
 */
function cleanTextForPdf(str) {
  if (!str) return '';
  
  let clean = str
    .replace(/α/g, 'alpha')
    .replace(/β/g, 'beta')
    .replace(/τ/g, 'tau')
    .replace(/θ/g, 'theta')
    .replace(/∅/g, 'null')
    .replace(/·/g, '*')
    .replace(/➔/g, '->')
    .replace(/Δ/g, 'delta')
    .replace(/Σ/g, 'sum')
    .replace(/≤/g, '<=')
    .replace(/≥/g, '>=')
    .replace(/≠/g, '!=')
    .replace(/≈/g, '~')
    .replace(/°/g, ' degrees')
    .replace(/±/g, '+/-')
    .replace(/¹/g, '^1')
    .replace(/²/g, '^2')
    .replace(/³/g, '^3')
    .replace(/⁻/g, '-')
    .replace(/⁺/g, '+')
    .replace(/π/g, 'pi')
    .replace(/½/g, '1/2')
    .replace(/—/g, '-')
    .replace(/–/g, '-')
    .replace(/•/g, '*');

  // Strip standard emojis
  clean = clean.replace(/[\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{1F000}-\u{1FFFF}\u{1F600}-\u{1F64F}\u{1F680}-\u{1F6FF}\u{1F1E6}-\u{1F1FF}]/gu, '');
  
  // Strip non-WinAnsi (>255) characters, converting known ones
  let finalClean = '';
  for (let i = 0; i < clean.length; i++) {
    const code = clean.charCodeAt(i);
    if (code <= 255) {
      finalClean += clean[i];
    } else {
      if (code === 0x2192) { // right arrow →
        finalClean += '->';
      } else if (code === 0x221E) { // infinity ∞
        finalClean += 'infinity';
      } else if (code === 0x2018 || code === 0x2019) { // single quotes
        finalClean += "'";
      } else if (code === 0x201C || code === 0x201D) { // double quotes
        finalClean += '"';
      } else {
        // Skip code
      }
    }
  }

  return finalClean.replace(/\s+/g, ' ').trim();
}

/**
 * addAllHeaders: Systematically draws a premium branded header on every page.
 */
function addAllHeaders(doc, title, module, icon, pageType) {
  const totalPages = doc.internal.getNumberOfPages();
  const cleanTitle = cleanTextForPdf(title);
  const cleanModule = cleanTextForPdf(module);
  const headerH = 22;

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    
    // Yellow banner background
    doc.setFillColor(...COLORS.yellow);
    doc.rect(0, 0, PAGE_WIDTH, headerH, 'F');
    
    // Bottom neo-brutalist border line
    doc.setDrawColor(...COLORS.black);
    doc.setLineWidth(1.0);
    doc.line(0, headerH, PAGE_WIDTH, headerH);

    // Title text
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(...COLORS.black);
    doc.text(cleanTitle, MARGIN.left, 14);

    // Module + Type badge
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    const badgeText = `${cleanModule}  |  ${pageType}`;
    const badgeW = doc.getTextWidth(badgeText) + 8;
    const badgeX = PAGE_WIDTH - MARGIN.right - badgeW;
    
    doc.setFillColor(...COLORS.white);
    doc.setDrawColor(...COLORS.black);
    doc.setLineWidth(0.6);
    doc.roundedRect(badgeX, 5, badgeW, 12, 1.5, 1.5, 'FD');
    doc.text(badgeText, badgeX + 4, 13);
  }
}

function addFooter(doc, pageNum, totalPages) {
  const y = 297 - 12;
  doc.setDrawColor(...COLORS.black);
  doc.setLineWidth(0.3);
  doc.line(MARGIN.left, y - 4, PAGE_WIDTH - MARGIN.right, y - 4);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.gray);
  doc.text('Generated by CS Simulator  |  Placement-Ready Study Material', MARGIN.left, y);
  doc.text(`Page ${pageNum} / ${totalPages}`, PAGE_WIDTH - MARGIN.right, y, { align: 'right' });
}

function addAllFooters(doc) {
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }
}

function checkPageBreak(doc, y, needed = 30) {
  if (y + needed > 297 - MARGIN.bottom) {
    doc.addPage();
    return MARGIN.top;
  }
  return y;
}

function drawSectionHeading(doc, text, y, color = COLORS.cyan) {
  y = checkPageBreak(doc, y, 22);
  const cleanText = cleanTextForPdf(text);
  
  // Neo-brutalist colored heading block
  doc.setFillColor(...color);
  doc.setDrawColor(...COLORS.black);
  doc.setLineWidth(0.8);
  doc.roundedRect(MARGIN.left, y, CONTENT_WIDTH, 12, 1.5, 1.5, 'FD');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.black);
  doc.text(cleanText, MARGIN.left + 4, y + 8.5);
  
  return y + 18; // Adequate vertical spacing below heading
}

function drawBodyText(doc, text, y, indent = 0) {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(...COLORS.darkGray);
  
  const maxWidth = CONTENT_WIDTH - indent;
  const lines = doc.splitTextToSize(cleanTextForPdf(text), maxWidth);
  
  for (const line of lines) {
    y = checkPageBreak(doc, y, 7);
    doc.text(line, MARGIN.left + indent, y);
    y += 5.5; // Improved line spacing
  }
  
  return y + 2.5; // Padding after paragraphs
}

function drawCodeBlock(doc, code, y) {
  const lines = code.split('\n');
  const lineHeight = 5.0;
  const padding = 6;
  const blockHeight = lines.length * lineHeight + padding * 2;
  
  y = checkPageBreak(doc, y, blockHeight + 6);
  
  // Neo-brutalist offset drop shadow
  doc.setFillColor(...COLORS.black);
  doc.roundedRect(MARGIN.left + 5.5, y - 0.5, CONTENT_WIDTH - 8, blockHeight, 2, 2, 'F');
  
  // Code block container
  doc.setFillColor(30, 30, 46); // Dark editor-style theme
  doc.setDrawColor(...COLORS.black);
  doc.setLineWidth(0.8);
  doc.roundedRect(MARGIN.left + 4, y - 2, CONTENT_WIDTH - 8, blockHeight, 2, 2, 'FD');
  
  doc.setFont('courier', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(205, 214, 244); // Catppuccin text color
  
  let currentY = y + padding + 1;
  for (const line of lines) {
    doc.text(cleanTextForPdf(line), MARGIN.left + 9, currentY);
    currentY += lineHeight;
  }
  
  return y + blockHeight + 5;
}

function drawDifficultyBadge(doc, difficulty, x, y) {
  const colors = {
    'Easy': COLORS.green,
    'Medium': COLORS.orange,
    'Hard': COLORS.pink,
  };
  const color = colors[difficulty] || COLORS.gray;
  const w = doc.getTextWidth(difficulty) + 8;
  
  doc.setFillColor(...color);
  doc.setDrawColor(...COLORS.black);
  doc.setLineWidth(0.4);
  doc.roundedRect(x, y - 3.5, w, 6, 1.5, 1.5, 'FD');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6.5);
  doc.setTextColor(...COLORS.black);
  doc.text(difficulty, x + 4, y + 0.5);
  
  return w;
}

/* ═══════════════════════════════════════
   SUBHEADING UTILITY
   ═══════════════════════════════════════ */
function drawSubheading(doc, text, y) {
  y = checkPageBreak(doc, y, 15);
  const cleanText = cleanTextForPdf(text);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(...COLORS.black);
  doc.text(cleanText, MARGIN.left + 2, y);
  
  doc.setDrawColor(210, 210, 210);
  doc.setLineWidth(0.3);
  doc.line(MARGIN.left + 2, y + 1.5, PAGE_WIDTH - MARGIN.right, y + 1.5);
  
  return y + 7.5;
}

/* ═══════════════════════════════════════
   ADVANCED MODULE APPENDIXES (DETAILED NOTES)
   ═══════════════════════════════════════ */
const OS_APPENDIX = [
  {
    heading: 'Advanced OS Concepts: Kernel Internals & Context Switching',
    content: '1. Monolithic vs. Microkernel Architectures: Monolithic kernels (e.g., Linux, Windows) execute all primary operating system services (VFS, IPC, memory management, scheduling) in a single, high-privilege kernel space. This design achieves peak execution speed but is susceptible to system-wide failure if any driver faults. Microkernels (e.g., Minix, QNX) run only critical path code (scheduling, minimal IPC) in kernel space, moving device drivers and filesystems to user space. This guarantees higher system resilience at the price of IPC overhead.\n2. Context Switching Latency: When the scheduler switches execution from one process to another, the CPU must save registers, stack pointers, and program counters into the Process Control Block (PCB). When switching processes, the CPU also flushes the TLB (Translation Lookaside Buffer). This invalidates cached virtual-to-physical address mappings, causing initial memory references in the newly scheduled process to experience cache cold starts and slow RAM access cycles (~0.1-10ms overhead).'
  },
  {
    heading: 'OS Placement Pro-Tips & Common Pitfalls',
    content: '• Starvation vs. Deadlock: In interviews, distinguish these clearly. Starvation is a condition where a thread is ready to run but is continuously bypassed by the scheduler in favor of other threads (the system overall still moves forward). Deadlock is a state of mutual block where two or more threads are waiting for resources held by each other, bringing system progress to a complete halt.\n• Thrashing Prevention: If page fault rates skyrocket while CPU utilization falls to near-zero, the system is thrashing. Prevent this by checking the Working Set Model size (sum of active pages accessed in time window Delta) against physical RAM. If it exceeds RAM, context-switch some processes to disk to free frames.'
  }
];

const DBMS_APPENDIX = [
  {
    heading: 'Advanced Database Concepts: Indexing & Query Optimizations',
    content: '1. Clustered vs. Non-Clustered Indexes: A clustered index physically dictates the on-disk storage order of the table data. Consequently, a table can possess only one clustered index (e.g., InnoDB primary key). Non-clustered indexes store search keys along with a pointer (row ID or clustered index key) back to the actual row. Querying via non-clustered indexes triggers a secondary disk read (bookmark lookup) unless the index contains all queried columns, making it a "covering index".\n2. Cost-Based Query Optimizer (CBO): Relational databases utilize statistics, histograms, and cost models to evaluate execution strategies (e.g., choosing an Index Scan over a Table Scan, or selecting a Hash Join over a Nested Loop Join). Outdated database statistics are a primary cause of sudden query degradation.'
  },
  {
    heading: 'DBMS Placement Pro-Tips & Common Pitfalls',
    content: '• Lost Update Problem: A classic concurrency pitfall where transactions T1 and T2 read the same value, modify it concurrently, and write it back. The last transaction to write overwrites the changes of the first. Prevent this by using optimistic concurrency control (a version/timestamp column checked on update) or pessimistic locks (using SELECT ... FOR UPDATE).\n• Low Cardinality Indexing: Avoid indexing columns with low cardinality (e.g., boolean values or status flags). The query optimizer will calculate that reading the index plus bookmark lookups costs more than a sequential table scan, rendering the index completely unused.'
  }
];

const OOP_APPENDIX = [
  {
    heading: 'Advanced Software Design: Composition vs. Inheritance',
    content: '1. Favor Composition over Inheritance: Inheritance establishes a rigid compile-time coupling between the parent and child classes (white-box reuse). Any change to the base class propagates down, risking subclass breaks. Composition relies on runtime interface injections (black-box reuse) to dynamically delegate behaviors. This respects the Open/Closed Principle and makes unit testing much easier through mock interfaces.\n2. Interface Segregation and LSP: Large, fat interfaces force implementing classes to write stub/empty methods or throw "UnsupportedOperationException", which violates both the Interface Segregation Principle (ISP) and the Liskov Substitution Principle (LSP).'
  },
  {
    heading: 'OOP Placement Pro-Tips & Common Pitfalls',
    content: '• Volatile in Double-Checked Locking: When writing a thread-safe Singleton, always mark the static instance variable as "volatile". Without volatile, the compiler or CPU instruction reordering can publish a reference to the Singleton block before its constructor finishes executing, causing other threads to read a partially initialized object.\n• Covariant Returns: In subclass overrides, returning a subtype of the parent method\'s return type is legal and encourages clean, typed code without breaking the Liskov Substitution contract.'
  }
];

const NETWORKS_APPENDIX = [
  {
    heading: 'Advanced Network Architectures: HTTP/3 & QUIC Protocol',
    content: '1. Head-of-Line (HoL) Blocking: In HTTP/2, multiple streams are multiplexed over a single TCP connection. If a single packet is lost in transit, TCP pauses the entire stream until the missing packet is retransmitted. HTTP/3 resolves this by running over QUIC (built on UDP). QUIC handles stream multiplexing independently; a packet loss in stream A has zero impact on streams B and C.\n2. TCP Congestion Control Algorithms: TCP uses algorithms like Reno, Cubic, or BBR (Google) to dynamically manage the transmission rate. It starts with Slow Start (doubling congestion window size every RTT) and switches to Congestion Avoidance (linear increment) once it crosses the slow start threshold (ssthresh) or detects packet loss.'
  },
  {
    heading: 'Networks Placement Pro-Tips & Common Pitfalls',
    content: '• DNS Caching Latency: Resolvers, OSes, and browsers aggressively cache IP lookups. When designing highly available systems, set a short Time-To-Live (TTL) for DNS records to ensure fast failover to backup servers when the primary goes down.\n• UDP vs. TCP Trade-offs: Do not recommend TCP for real-time multiplayer gaming, VoIP, or DNS lookups. The overhead of the 3-way handshake, 4-way teardown, and retransmissions degrades real-time responsiveness.'
  }
];

const SD_APPENDIX = [
  {
    heading: 'Advanced System Design: Distributed Consistencies & Scaling',
    content: '1. Eventual Consistency in Microservices: Databases-per-service patterns make ACID transactions across multiple boundaries impossible without blocking 2-Phase Commits (2PC), which degrade throughput. Use the Saga Pattern (orchestrated or choreographed) to trigger sequential local transactions. If any step fails, run compensating transactions to roll back the state.\n2. Consistent Hashing ring: Basic consistent hashing ring mapping can create hot nodes. Resolve this by mapping each physical node to 100-200 virtual nodes on the ring, ensuring uniform hash distribution.'
  },
  {
    heading: 'System Design Placement Pro-Tips & Common Pitfalls',
    content: '• CAP Theorem Realities: In the presence of a network partition (P), distributed databases must choose between Availability (A) or Consistency (C). CP databases (MongoDB, HBase) reject writes to keep data consistent. AP databases (Cassandra, DynamoDB) accept writes but serve eventually consistent stale reads.\n• Sharding Hotspots: Never shard databases based on date/time fields. Doing so ensures all new writes hit only the newest database shard. Instead, shard on high-cardinality keys like user_id.'
  }
];

/* ═══════════════════════════════════════
   COMBINED STUDY GUIDE PDF GENERATOR
   ═══════════════════════════════════════ */
export function generateStudyGuidePdf(topicKey) {
  // Determine category and merge keys
  let categoryPrefix = '';
  let masterTitle = '';
  let masterModule = '';
  
  if (topicKey.startsWith('os/')) {
    categoryPrefix = 'os/';
    masterTitle = 'Operating Systems (OS) Complete Placement Guide';
    masterModule = 'Operating Systems';
  } else if (topicKey.startsWith('dbms/')) {
    categoryPrefix = 'dbms/';
    masterTitle = 'Database Management Systems (DBMS) Complete Placement Guide';
    masterModule = 'Database Management Systems';
  } else if (topicKey.startsWith('oops/')) {
    categoryPrefix = 'oops/';
    masterTitle = 'Object-Oriented Programming & Design Patterns Complete Placement Guide';
    masterModule = 'Object-Oriented Programming';
  } else if (topicKey.startsWith('networks/')) {
    categoryPrefix = 'networks/';
    masterTitle = 'Computer Networks (CN) Complete Placement Guide';
    masterModule = 'Computer Networks';
  } else if (topicKey.startsWith('systemdesign/')) {
    categoryPrefix = 'systemdesign/';
    masterTitle = 'System Design & High-Scale Architectures Complete Placement Guide';
    masterModule = 'System Design';
  } else {
    categoryPrefix = topicKey;
    masterTitle = 'Technical Interview Prep & CS Fundamentals Master Guide';
    masterModule = 'Interview Prep';
  }

  let keysToMerge = [];
  if (categoryPrefix.endsWith('/')) {
    keysToMerge = Object.keys(NOTES_DATA).filter(k => k.startsWith(categoryPrefix));
  } else {
    keysToMerge = [topicKey];
  }

  const mergedFullNotesSections = [];
  const mergedQuestions = [];
  const mergedKeyPoints = [];
  const mergedFormulas = [];
  const mergedComparisons = [];
  const mergedMnemonics = [];

  keysToMerge.forEach(key => {
    const subData = NOTES_DATA[key];
    if (!subData) return;

    if (subData.fullNotes?.sections) {
      subData.fullNotes.sections.forEach(sec => {
        mergedFullNotesSections.push({
          heading: `${subData.title} - ${sec.heading}`,
          content: sec.content,
          codeSnippet: sec.codeSnippet
        });
      });
    }

    if (subData.interviewPrep?.questions) {
      subData.interviewPrep.questions.forEach(q => {
        mergedQuestions.push({
          q: `[${subData.title}] ${q.q}`,
          a: q.a,
          difficulty: q.difficulty
        });
      });
    }

    if (subData.cheatSheet?.keyPoints) {
      subData.cheatSheet.keyPoints.forEach(p => {
        mergedKeyPoints.push(`[${subData.title}] ${p}`);
      });
    }

    if (subData.cheatSheet?.formulas) {
      subData.cheatSheet.formulas.forEach(f => {
        mergedFormulas.push(`[${subData.title}] ${f}`);
      });
    }

    if (subData.cheatSheet?.comparisons) {
      subData.cheatSheet.comparisons.forEach(c => {
        mergedComparisons.push(c);
      });
    }

    if (subData.cheatSheet?.mnemonics) {
      subData.cheatSheet.mnemonics.forEach(m => {
        mergedMnemonics.push(m);
      });
    }
  });

  const data = {
    title: masterTitle,
    module: masterModule,
    icon: '📘',
    cheatSheet: {
      keyPoints: mergedKeyPoints,
      formulas: mergedFormulas,
      comparisons: mergedComparisons,
      mnemonics: mergedMnemonics
    },
    fullNotes: {
      sections: mergedFullNotesSections
    },
    interviewPrep: {
      questions: mergedQuestions
    }
  };

  const doc = new jsPDF('p', 'mm', 'a4');
  let y = MARGIN.top + 6;

  // 1. Premium Header Title block
  doc.setFillColor(...COLORS.yellow);
  doc.setDrawColor(...COLORS.black);
  doc.setLineWidth(0.8);
  doc.roundedRect(MARGIN.left, y, CONTENT_WIDTH, 16, 2, 2, 'FD');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.black);
  doc.text(cleanTextForPdf(data.title) + " - Placement Study Guide", MARGIN.left + 5, y + 10.5);
  y += 24;

  // Module info tag
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.gray);
  const cleanModule = cleanTextForPdf(data.module);
  doc.text(`Module: ${cleanModule}  |  Type: All-In-One Placement Companion`, MARGIN.left, y);
  y += 8;

  // ----------------------------------------------------
  // PART 1: QUICK REFERENCE & CHEAT SHEET
  // ----------------------------------------------------
  if (data.cheatSheet) {
    y = drawSectionHeading(doc, 'Part 1: Quick Reference & Cheat Sheet', y, COLORS.yellow);
    
    // Key Points
    if (data.cheatSheet.keyPoints?.length) {
      y = drawSubheading(doc, 'Key Points', y);
      data.cheatSheet.keyPoints.forEach((point) => {
        y = checkPageBreak(doc, y, 10);
        
        doc.setFillColor(...COLORS.black);
        doc.circle(MARGIN.left + 4, y - 1, 0.9, 'F');
        
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(...COLORS.darkGray);
        
        const lines = doc.splitTextToSize(cleanTextForPdf(point), CONTENT_WIDTH - 12);
        for (const line of lines) {
          doc.text(line, MARGIN.left + 8, y);
          y += 5.0;
        }
        y += 1.5;
      });
      y += 3;
    }

    // Formulas & Complexities
    if (data.cheatSheet.formulas?.length) {
      y = drawSubheading(doc, 'Formulas & Complexities', y);
      data.cheatSheet.formulas.forEach((formula) => {
        const fLines = doc.splitTextToSize(cleanTextForPdf(formula), CONTENT_WIDTH - 12);
        const fLineHeight = 4.8;
        const fH = fLines.length * fLineHeight + 6;
        
        y = checkPageBreak(doc, y, fH + 5);
        
        doc.setFillColor(248, 249, 251);
        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.4);
        doc.roundedRect(MARGIN.left + 4, y - 3, CONTENT_WIDTH - 8, fH, 1.5, 1.5, 'FD');
        
        doc.setFont('courier', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(30, 30, 46);
        
        let currentY = y + 1.5;
        for (const line of fLines) {
          doc.text(line, MARGIN.left + 8, currentY);
          currentY += fLineHeight;
        }
        y += fH + 2;
      });
      y += 2;
    }

    // Comparisons (Dynamic Auto-wrapping Table)
    if (data.cheatSheet.comparisons?.length) {
      y = drawSubheading(doc, 'Comparisons', y);
      data.cheatSheet.comparisons.forEach((comp) => {
        const colW = (CONTENT_WIDTH - 8) / 2;
        const leftHeader = cleanTextForPdf(comp.left);
        const rightHeader = cleanTextForPdf(comp.right);
        
        const leftHeaderLines = doc.splitTextToSize(leftHeader, colW - 6);
        const rightHeaderLines = doc.splitTextToSize(rightHeader, colW - 6);
        
        const headerLinesMax = Math.max(leftHeaderLines.length, rightHeaderLines.length);
        const headerH = headerLinesMax * 4.5 + 6;
        
        y = checkPageBreak(doc, y, headerH + 20);
        
        // Draw table header cells
        doc.setFillColor(...COLORS.yellow);
        doc.setDrawColor(...COLORS.black);
        doc.setLineWidth(0.8);
        doc.rect(MARGIN.left + 2, y, colW, headerH, 'FD');
        doc.rect(MARGIN.left + 2 + colW, y, colW, headerH, 'FD');
        
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(...COLORS.black);
        
        leftHeaderLines.forEach((line, idx) => {
          doc.text(line, MARGIN.left + 5, y + 4.5 + idx * 4.5);
        });
        rightHeaderLines.forEach((line, idx) => {
          doc.text(line, MARGIN.left + 5 + colW, y + 4.5 + idx * 4.5);
        });
        
        y += headerH;
        
        // Criteria rows
        comp.criteria.forEach((c, ci) => {
          const parts = c.split(' vs ');
          const leftText = cleanTextForPdf(parts[0] || c);
          const rightText = cleanTextForPdf(parts[1] || '');
          
          const leftLines = doc.splitTextToSize(leftText, colW - 6);
          const rightLines = doc.splitTextToSize(rightText, colW - 6);
          
          const maxLines = Math.max(leftLines.length, rightLines.length);
          const rowH = maxLines * 4.5 + 5;
          
          y = checkPageBreak(doc, y, rowH);
          
          const bg = ci % 2 === 0 ? [255, 255, 255] : [245, 245, 250];
          doc.setFillColor(...bg);
          doc.setDrawColor(...COLORS.black);
          doc.setLineWidth(0.6);
          
          doc.rect(MARGIN.left + 2, y, colW, rowH, 'FD');
          doc.rect(MARGIN.left + 2 + colW, y, colW, rowH, 'FD');
          
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(8);
          doc.setTextColor(...COLORS.darkGray);
          
          leftLines.forEach((line, idx) => {
            doc.text(line, MARGIN.left + 5, y + 4.5 + idx * 4.5);
          });
          rightLines.forEach((line, idx) => {
            doc.text(line, MARGIN.left + 5 + colW, y + 4.5 + idx * 4.5);
          });
          
          y += rowH;
        });
        
        y += 6;
      });
    }

    // Mnemonics
    if (data.cheatSheet.mnemonics?.length) {
      y = drawSubheading(doc, 'Mnemonics & Memory Aids', y);
      data.cheatSheet.mnemonics.forEach((m) => {
        const mLines = doc.splitTextToSize(cleanTextForPdf(m), CONTENT_WIDTH - 16);
        const mLineHeight = 4.8;
        const mPadding = 5;
        const mH = mLines.length * mLineHeight + mPadding * 2;
        
        y = checkPageBreak(doc, y, mH + 6);
        
        doc.setFillColor(235, 247, 236);
        doc.setDrawColor(...COLORS.green);
        doc.setLineWidth(0.5);
        doc.roundedRect(MARGIN.left + 4, y - 3, CONTENT_WIDTH - 8, mH, 1.5, 1.5, 'FD');
        
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(8.5);
        doc.setTextColor(40, 115, 45); // Forest green
        
        let currentY = y + mPadding - 1;
        for (const line of mLines) {
          doc.text(`* ${line}`, MARGIN.left + 8, currentY);
          currentY += mLineHeight;
        }
        y += mH + 4;
      });
    }
  }

  // ----------------------------------------------------
  // PART 2: COMPREHENSIVE STUDY NOTES
  // ----------------------------------------------------
  y = checkPageBreak(doc, y, 40);
  y = drawSectionHeading(doc, 'Part 2: Comprehensive Study Notes', y, COLORS.cyan);
  
  if (data.fullNotes?.sections?.length) {
    data.fullNotes.sections.forEach((section, i) => {
      y = drawSubheading(doc, `${i + 1}. ${section.heading}`, y);
      y = drawBodyText(doc, section.content, y, 2);
      
      if (section.codeSnippet) {
        y = drawCodeBlock(doc, section.codeSnippet, y);
      }
      y += 4;
    });
  }

  // ----------------------------------------------------
  // PART 3: PLACEMENT INTERVIEW PREP Q&A
  // ----------------------------------------------------
  y = checkPageBreak(doc, y, 40);
  y = drawSectionHeading(doc, 'Part 3: Placement Interview Prep Q&A', y, COLORS.pink);
  
  if (data.interviewPrep?.questions?.length) {
    data.interviewPrep.questions.forEach((q, i) => {
      y = checkPageBreak(doc, y, 40);
      
      // Question label + difficulty badge
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(...COLORS.black);
      
      const qLabel = `Q${i + 1}.`;
      doc.text(qLabel, MARGIN.left, y);
      const labelW = doc.getTextWidth(qLabel) + 3;
      drawDifficultyBadge(doc, q.difficulty, MARGIN.left + labelW, y);
      y += 5.5;

      // Question text
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(...COLORS.black);
      const qLines = doc.splitTextToSize(cleanTextForPdf(q.q), CONTENT_WIDTH - 4);
      for (const line of qLines) {
        y = checkPageBreak(doc, y, 7);
        doc.text(line, MARGIN.left + 2, y);
        y += 5.0;
      }
      y += 2.5;

      // Answer block configuration
      doc.setFillColor(...COLORS.lightGray);
      const ansLines = doc.splitTextToSize(cleanTextForPdf(q.a), CONTENT_WIDTH - 16);
      const ansLineHeight = 4.8;
      const ansPadding = 5;
      const ansBlockH = ansLines.length * ansLineHeight + ansPadding * 2;
      
      y = checkPageBreak(doc, y, ansBlockH + 5);
      
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.4);
      doc.roundedRect(MARGIN.left + 2, y - 3, CONTENT_WIDTH - 4, ansBlockH, 1.5, 1.5, 'FD');
      
      // Left vertical accent bar
      doc.setFillColor(...COLORS.green);
      doc.rect(MARGIN.left + 2, y - 3, 2.5, ansBlockH, 'F');

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...COLORS.darkGray);
      
      let currentY = y + ansPadding - 1;
      for (const line of ansLines) {
        doc.text(line, MARGIN.left + 8, currentY);
        currentY += ansLineHeight;
      }
      
      y += ansBlockH + 3;
    });
  }

  // ----------------------------------------------------
  // PART 4: PLACEMENT MASTERCLASS (DETAILED NOTES APPENDIX)
  // ----------------------------------------------------
  let appendix = [];
  if (topicKey.startsWith('os/')) {
    appendix = OS_APPENDIX;
  } else if (topicKey.startsWith('dbms/')) {
    appendix = DBMS_APPENDIX;
  } else if (topicKey.startsWith('oops/')) {
    appendix = OOP_APPENDIX;
  } else if (topicKey.startsWith('networks/')) {
    appendix = NETWORKS_APPENDIX;
  } else if (topicKey.startsWith('systemdesign/') || topicKey === 'interview') {
    appendix = SD_APPENDIX;
  }

  if (appendix.length > 0) {
    y = checkPageBreak(doc, y, 40);
    y = drawSectionHeading(doc, 'Part 4: Placement Masterclass (Advanced Concepts)', y, COLORS.green);
    
    appendix.forEach((item) => {
      y = drawSubheading(doc, item.heading, y);
      y = drawBodyText(doc, item.content, y, 2);
      y += 4;
    });
  }

  // Finish PDF layout
  addAllHeaders(doc, data.title, data.module, data.icon, 'Placement Study Guide');
  addAllFooters(doc);
  
  const filename = `${data.title.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '_')}_Study_Guide.pdf`;
  doc.save(filename);
  return filename;
}

